### ISSUE TITLE
truncate ridiculous long descriptions

### ISSUE THREAD

**Issue by rdela** [beakerbrowser/hashbase#80]
Need to truncate ridiculous long descriptions

https://hashbase.io/ricky
https://hashbase.io/ricky/gif

This CSS may do the trick to avoid list column spill 

```css
.archive-list .description {
/* … */
text-overflow: ellipsis;
width: 37rem;
overflow-x: hidden;
max-width: 100%;
}
```

~~in PR process now~~
